// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKgmIYK89vsBmgOucfC7Zklsz2aijoZYQ',
    appId: '1:167670209063:web:5376dd74f06be419e44c02',
    messagingSenderId: '167670209063',
    projectId: 'stamp-app-5495e',
    authDomain: 'stamp-app-5495e.firebaseapp.com',
    storageBucket: 'stamp-app-5495e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOZ6spZXs2AKQmkYfkdErH9J-V-UF2aU',
    appId: '1:167670209063:android:8974eb78553c9c95e44c02',
    messagingSenderId: '167670209063',
    projectId: 'stamp-app-5495e',
    storageBucket: 'stamp-app-5495e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbW7liZMisTL0q7N9D4UQX-MoY6z8afsw',
    appId: '1:167670209063:ios:9e0d3e93f6ded283e44c02',
    messagingSenderId: '167670209063',
    projectId: 'stamp-app-5495e',
    storageBucket: 'stamp-app-5495e.firebasestorage.app',
    iosBundleId: 'com.example.stampApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKgmIYK89vsBmgOucfC7Zklsz2aijoZYQ',
    appId: '1:167670209063:web:84a14db38d6cf066e44c02',
    messagingSenderId: '167670209063',
    projectId: 'stamp-app-5495e',
    authDomain: 'stamp-app-5495e.firebaseapp.com',
    storageBucket: 'stamp-app-5495e.firebasestorage.app',
  );

}